spring:
  application:
    name: wechat-service-provider
dubbo:
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    timeout: 60000
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 15000
    version: 1.0
server:
  port: 8000
